ja_social/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import login

from .views import UserRegisterView, VolunteerRecordLogView, logout_view, UserProfileView, profile_redirect, ProfileEditView, PhotoUploadView, PhotoGalleryView, HomePageTemplate

urlpatterns = [
    url(r'^$', HomePageTemplate.as_view(), name="home_page"),

    url(r'^account/register$', UserRegisterView.as_view(), name="account_registration"),
    url(r'^account/success$', TemplateView.as_view(template_name="success.html"), name="account success page"),
    url(r'^account/profile/(?P<pk>[0-9]+)', UserProfileView.as_view(), name='user_view'),
    url(r'^account/update/(?P<pk>[0-9]+)', ProfileEditView.as_view(), name='user_update'),
    url(r'^account/login$', login, {'template_name': 'login.html'}, name='login_page'),
    url(r'^account/logout$', logout_view, name='logout_page'),
    url(r'^account/photo/upload$', PhotoUploadView.as_view(), name='photo_upload'),
    url(r'^account/photo/gallery$', PhotoGalleryView.as_view(), name='photo_gallery'),

    url(r'^profile/', profile_redirect, name='profile_redirect'),

    url(r'^volunteer/success$', TemplateView.as_view(template_name="success.html"), name="volunteer success page"),
    url(r'^volunteer/log$', VolunteerRecordLogView.as_view(), name="volunteer_record_log"),

    url(r'^profile_pics/(?P<pk>[0-9]+)', profile_redirect, name='profile_redirect'),

]

junior_achievement/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^social/', include('ja_social.urls', namespace="ja_social"),),
    url(r'^accounts/', include('ja_social.urls', namespace="ja_social"),),
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name="home.html"), name="home_page"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ja_social/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse_lazy


import datetime

MAX_CHAR_LENGTH = 50

COUNTY_OPTIONS = (
    ("Alamance", "Alamance"),
    ("Forsyth", "Forsyth"),
    ("Guilford", "Guilford"),
    ("Montgomery", "Montgomery"),
    ("Randolph", "Randolph"),
    ("Rockingham", "Rockingham"),
    ("Other", "Other")
)

JA_PROGRAM_OPTIONS = (
    ("JA Ourselves", "JA Ourselves"),
    ("JA Our Families", "JA Our Families"),
    ("JA Our Community", "JA Our Community"),
    ("JA Our City", "JA Our City"),
    ("JA Our Region", "JA Our Region"),
    ("JA Our Nation", "JA Our Nation"),
    ("JA Economics for Success", "JA Economics for Success"),
    ("JA Global Marketplace - Kit Based", "JA Global Marketplace - Kit Based"),
    ("JA Global Marketplace - Blended Model", "JA Global Marketplace - Blended Model"),
    ("JA It's My Future", "JA It's My Future"),
    ("JA Be Entrepreneurial", "JA Be Entrepreneurial"),
    ("JA Career", "JA Career"),
    ("JA Company Program - Blended Model", "JA Company Program - Blended Model"),
    ("JA Economics", "JA Economics"),
    ("JA Exploring Economics", "JA Exploring Economics"),
    ("JA Job Shadow", "JA Job Shadow"),
    ("JA Personal Financial", "JA Personal Financial"),
    ("JA Personal Financial - Blended Model", "JA Personal Financial - Blended Model"),
    ("JA Titan", "JA Titan")

)


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="profile")
    company = models.CharField(max_length=MAX_CHAR_LENGTH, blank=True, null=True)
    profile_pic = models.ImageField(upload_to="uploads/profile_pics/", null=True, default=None)
    activation_key = models.CharField(max_length=40, default="")
    key_expires = models.DateTimeField(default=datetime.date.today)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.user.get_username()

    def get_absolute_url(self):
        return reverse_lazy('ja_social:user_view', kwargs={'pk': self.pk})


class VolunteerRecord(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    county = models.CharField(max_length=MAX_CHAR_LENGTH, choices=COUNTY_OPTIONS)
    school_name = models.CharField(max_length=MAX_CHAR_LENGTH, blank=False, null=False)
    JA_program = models.CharField(max_length=MAX_CHAR_LENGTH, blank=False, null=False, default="", choices=JA_PROGRAM_OPTIONS)
    hours = models.PositiveIntegerField(blank=False, null=False, default=0)
    date = models.DateField(blank=False, null=False, default=datetime.date.today)
    verified = models.BooleanField(blank=False, null=False, default=False)

    def __str__(self):
        return "%s: %s %s (%d)" % (self.user_profile.user.get_full_name(), self.school_name, self.JA_program, self.hours)


class PhotoRecord(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="uploads/gallery_pictures/", blank=False, null=False)
    date_uploaded = models.DateField(default=datetime.date.today, null=False)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

models.signals.post_save.connect(create_user_profile, sender=User)

ja_social/forms.py
from django import forms
from django.contrib.auth.models import User

from datetime import datetime

import hashlib
import random

class UserForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': "A user with that username already exists.",
        'password_mismatch': "The two password fields didn't match.",
    }
    username = forms.RegexField(label="Username", max_length=30,
                                regex=r'^[\w]+$',
                                help_text=r"Required. 30 characters or fewer. Letters, digits and _ only.",
                                error_messages={'invalid': r"This value may contain only letters, numbers and _ characters."})
    email = forms.EmailField(label="Email", max_length=256)
    password1 = forms.CharField(label="Password",
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput,
                                help_text="Enter the same password as above, for verification.")

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.is_active = False
        user.set_password(self.cleaned_data["password1"])

        #
        # Assistance for generating activation key from: http://stackoverflow.com/questions/24935271/django-custom-user-email-account-verification
        #

        # salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
        # usernamesalt = self.cleaned_data["username"]
        # user.activation_key=hashlib.sha1(salt+usernamesalt).hexdigest()
        # user.key_expires=datetime.datetime.strftime(datetime.datetime.now() + datetime.timedelta(days=2), "%Y-%m-%d %H:%M:%S")

        if commit:
            user.save()
        return user

    # def sendEmail(self, datas):
    #     link="http://yourdomain.com/activate/"+datas['activation_key']
    #     c=Context({'activation_link':link,'username':datas['username']})
    #     f = open(MEDIA_ROOT+datas['email_path'], 'r')
    #     t = Template(f.read())
    #     f.close()
    #     message=t.render(c)
    #     #print unicode(message).encode('utf8')
    #     send_mail(datas['email_subject'], message, 'yourdomain <no-reply@yourdomain.com>', [datas['email']], fail_silently=False)

ja_social/views.py
from django.views.generic import CreateView, DetailView, UpdateView, ListView, TemplateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from django.db.models import Sum

from .forms import UserForm
from .models import VolunteerRecord, UserProfile, PhotoRecord



class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **kwargs):
        view = super(LoginRequiredMixin, cls).as_view(**kwargs)
        return login_required(view)


class UserRegisterView(CreateView):
    template_name = "user_register.html"
    model = User
    success_url = reverse_lazy('ja_social:home_page')
    form_class = UserForm


class UserProfileView(DetailView):
    model = UserProfile
    template_name = "user_detail.html"

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['hours'] = VolunteerRecord.objects.all()
        context['photos'] = PhotoRecord.objects.filter(user_profile=self.request.user.profile)
        context['hours_total'] = VolunteerRecord.objects.filter(user_profile=self.request.user.profile, verified= True).aggregate(Sum('hours'))
        return context


class ProfileEditView(LoginRequiredMixin, UpdateView):
    template_name = "user_profile_edit.html"
    model = UserProfile
    fields = ['company']

    def get_context_data(self, **kwargs):
        context = super(ProfileEditView, self).get_context_data(**kwargs)
        context['hours'] = VolunteerRecord.objects.all()
        context['photos'] = PhotoRecord.objects.filter(user_profile=self.request.user.profile);
        context['hours_total'] = VolunteerRecord.objects.filter(user_profile=self.request.user.profile, verified= True).aggregate(Sum('hours'))
        return context


class VolunteerRecordLogView(CreateView):
    template_name = "volunteer_log.html"
    model = VolunteerRecord
    fields = ['county', 'school_name', 'JA_program', 'hours']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user_profile = self.request.user.profile
        obj.save()
        return HttpResponseRedirect(reverse_lazy('ja_social:user_view', args=(self.request.user.pk,)))


class PhotoUploadView(CreateView):
    template_name = "photo_upload.html"
    model = PhotoRecord
    fields = ['photo']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user_profile = self.request.user.profile
        obj.save()
        return HttpResponseRedirect(reverse_lazy('ja_social:user_view', args=(self.request.user.pk,)))


class PhotoGalleryView(ListView):
    template_name = "photo_gallery.html"
    model = PhotoRecord


class HomePageTemplate(TemplateView):
    template_name = "home.html"
    def get_context_data(self, **kwargs):
        context = super(HomePageTemplate, self).get_context_data(**kwargs)
        context['photos'] = PhotoRecord.objects.all()
        return context


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('ja_social:home_page'))


def profile_redirect(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('ja_social:user_view', args=(request.user.pk,)))
    return HttpResponseRedirect(reverse('ja_social:home_page'))

ja_social/templates/base_html.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %} | Junior Achievement of the Triad</title>
    {% block stylesheets %}{% endblock %}
    <meta charset="UTF-8">

    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'ja_social/css/home-style.css'%}">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Datatables -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
  <script src="http://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

    <!-- fontawesome -->
  <script src="https://use.fontawesome.com/ed51a65b15.js"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid" id="nav-container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/social">
          <img alt="logo" src="{% static 'ja_social/img/ja-logo-sticky.png'%}">
        </a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              {% if user.is_authenticated %}
                {% ifequal user.profile.profile_pic None %}
                    <img id="avatar" src="{% static 'ja_social/img/avatar.png'%}"/>
                {% else %}
                    <img id="avatar" src="{{ user.profile.profile_pic.url }}"/>
                {% endifequal %}
              {% else %}
                <img id="avatar" src="{% static 'ja_social/img/avatar.png'%}"/>
              {% endif %}
              <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
              {% if user.is_authenticated %}
                <li><a href="{% url 'ja_social:user_view' user.pk %}">Profile: {{ user.first_name }}  {{ user.last_name }}</a></li>
                <li><a href="{% url 'ja_social:user_update' user.pk %}">Edit Profile</a></li>
                <li><a href="{% url 'ja_social:logout_page' %}">Log Out</a></li>
              {% else %}
                  <li><a href="{% url 'ja_social:login_page'%}">Login</a></li>
                  <li><a href="{% url 'ja_social:account_registration'%}">Register</a></li>
              {% endif %}
          </ul>
        </li>
        </ul>
      </div>
    </div>
  </nav>
      <div id="filler">
    <!-- empty div the same height as the nav bar -->
  </div>
    <div id="content">
        {% block content %} {% endblock %}
    </div>
  <div id="footer">
    <div id="links" class="row">
      <div class="col-sm-4 text-center">
        <h3>Quick Links</h3>
        <p>
          <a href="https://triadja.org/invest/">Invest</a>
        </p>
        <p>
          <a href="https://triadja.org/classroom-volunteers/">Volunteer</a>
        </p>
        <p>
          <a href="https://triadja.org/contact/">Contact</a>
        </p>
        <p>
          <a href="https://triadja.org/">triadja.org</a>
        </p>
      </div>
      <div id="social-icons" class="col-sm-4">
        <a class="btn btn-social-icon btn-facebook icon" href="https://www.facebook.com/TriadJuniorAchievement">
            <span class="fa fa-facebook"></span>
        </a>
        <a class="btn btn-social-icon btn-linkedin icon" href="https://www.linkedin.com/company/triadja">
            <span class="fa fa-linkedin"></span>
        </a>
        <a class="btn btn-social-icon btn-instagram icon" href="https://www.instagram.com/Triad_JA/">
            <span class="fa fa-instagram"></span>
        </a>
        <a class="btn btn-social-icon btn-twitter icon" href="https://twitter.com/Triad_JA">
            <span class="fa fa-twitter"></span>
        </a>
      </div>
      <div class="col-sm-4 text-center">
        <h3>Contact</h3>
        <p>Junior Achievement of the Triad</p>
        <p>3220 Northline Ave.</p>
        <p>Greensboro NC 27408</p>
        <p>Email: info@triadja.org</p>
        <p>336-299-4339</p>
      </div>
    </div>
    <p><small>© 2016 Junior Achievement of the Triad. All rights reserved.</small></p>
  </div>
</body>
</html>

ja_social/templates/home.html
{% extends 'base_html.html' %}
{% load static  %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1 id="featured-title">Featured Volunteer</h1>
    <div class="row">
      <div class="col-sm-12">
        <img id="featured-volunteer" src="{% static 'ja_social/img/volunteer.jpg' %}"/>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <h3>"Voluteering my time has been one of the most rewarding experiences of my life."</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <h3>-Joe Nobody</h3>
      </div>
    </div>
  </div>
<div class="row">
    <a href="https://triadja.org/classroom-volunteers/">
        <div id="volunteer-square" class="col-sm-6 text-center">
        <img src="{% static 'ja_social/img/volunteer-featured.png'%}"  />
        <h1 id="vol-message">Join the Action</h1>
        </div>
    </a>
    <div class="col-sm-6 text-center">
        {% for photo in photos %}
        <div class="col-xs-6 col-md-3 gal-square">
          <a href="{% url 'ja_social:photo_gallery' %}" class="thumbnail">
            <img src="{{ photo.photo.url }}" />
          </a>
        </div>
        {% endfor %}
        <h1 id="gal-message">Visit the Gallery</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 text-center">
      <!-- SnapWidget -->
      <script src="https://snapwidget.com/js/snapwidget.js"></script>
      <iframe src="https://snapwidget.com/embed/274876" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>
    </div>

      <div class="col-sm-6 text-center">
      <!--
      found a widget generated from Twitter directly
      -->
        <h3>Tweet with #TriadJA for your tweets to show up here!</h3>
        <a class="twitter-timeline"  href="https://twitter.com/hashtag/triadja" data-widget-id="790091606594650112">#triadja Tweets</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
  </div>
{% endblock %}

ja_social/templates/login.html
{% extends 'base_html.html' %}
{% load static  %}
{% block title %}
Login
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'ja_social/css/login-style.css'%}">
{% endblock %}
{% block content %}
<div class="row">
   <div class="col-sm-8 col-sm-offset-2">
      <div class="jumbotron">
         <!-- Login adapted from https://codepen.io/anon/pen/qagbKb (codepen is MIT license) -->
         <div class="wrapper">

            {% if form.errors %}
            <p class="error">* Invalid username/password. Please try again. *</p>
            {% endif %}
            <form method="post" action="{% url 'ja_social:login_page' %}" id="loginForm" class="form-signin">
               {% csrf_token %}
                <h2 id="loginHeader">Login Form</h2>
               <table>
                  <tr>
                     <td>{{ form.username.label_tag }}</td>
                     <td>{{ form.username }}</td>
                  </tr>
                  <tr>
                     <td>{{ form.password.label_tag }}</td>
                     <td>{{ form.password }}</td>
                  </tr>
               </table>
               <input id="submit-button" class="btn btn-lg btn-primary btn-block" type="submit" value="Login" />
               <input type="hidden" name="next" value="{{ next }}" />
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock %}

ja_social/templates/photo_gallery.html
{% extends 'base_html.html' %}
{% load static  %}
{% block title %}Photo Gallery{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'ja_social/css/photo-gallery-style.css'%}">
{% endblock %}
{% block content %}

<div class="jumbotron">
    <h1>Image of the Week</h1>
    <div class="row">
      <div class="col-sm-12 fill">
        <img id="feature-image" src="{% static 'ja_social/img/elementary-featured.jpg'%}" />
      </div>
    </div>
    <h3>This is Jimmy, one of our elementary students who is very excited about taking charge of his future!</h3>
  </div>
  <div class="container" class="row">
    <h1>Community Photos</h1>
    <div class="row">
        {% for photo in object_list %}
        <div class="col-xs-6 col-md-3">
          <a href="#" class="thumbnail">
            <img src="{{ photo.photo.url }}" />
          </a>
        </div>
        {% endfor %}
    </div>
  </div>

{% endblock %}

ja_social/templates/photo_upload.html
{% extends 'base_html.html' %}

{% load static %}

{% block title %}
Photo Upload
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'ja_social/css/photo-upload-style.css'%}">
{% endblock %}

{% block content %}
<div class="photo_container container">
    <h1>Upload Photo</h1>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Upload" />
            </form>
        </div>
    </div>

{% endblock %}

ja_social/templates/success.html
{% extends 'base_html.html' %}

{% block title %}
Success
{% endblock %}

{% block content %}
<h1>SUCCESS</h1>
{% endblock %}

ja_social/templates/user_profile_edit.html
{% extends 'base_html.html' %}
{% load static  %}
{% block title %}Update {{ object.user.first_name }}  {{ object.user.last_name }}'s Profile{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'ja_social/css/profile-style.css'%}">
{% endblock %}
{% block content %}
  <div class="jumbotron">
    <div class="row">
      <div class="col-sm-2 col-sm-offset-2">
            {% ifequal object.profile_pic None %}
                <img id="profile-pic" src="{% static 'ja_social/img/avatar.png'%}">
            {% else %}
                <img id="profile-pic" src="{{ object.profile_pic.url }}"/>
            {% endifequal %}
      </div>
      <div class="col-sm-4">
            <h1>{{ object.user.first_name }}  {{ object.user.last_name }}</h1>
            <div class="fieldWrapper">
                <form action="" method="POST">{% csrf_token %}
    {{ form.company.errors }}
    {{ form.company.label_tag }}
    {{ form.company }}
                    <input type="submit" value="Update" />
                    </form>
</div>
            <p>Date Joined: {{ object.user.date_joined | date }}</p>
      </div>
      <div class="col-sm-2">
          <div class="row">
              {% if hours_total.hours__sum >= 100 %}
                <img class="badge-img" src="{% static 'ja_social/img/100hours.png'%}"/>
              {% elif hours_total.hours__sum >= 25 %}
                <img class="badge-img" src="{% static 'ja_social/img/25hours.png'%}"/>
              {% elif hours_total.hours__sum >= 10 %}
                <img class="badge-img" src="{% static 'ja_social/img/10hours.png'%}"/>
              {% endif %}
              {% if object.profile.featured %}
                <img class="badge-img" src="{% static 'ja_social/img/featured-volunteer.png'%}"/>
              {% endif %}
          </div>
          <div class="row">
              <h1>Total hours: {{hours_total.hours__sum}}</h1>
          </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function(){
        $('#hours-table').DataTable();
    });
  </script>
<div id="hours-container" class="row">
    <h1>Hours <span class="edit_symbol"><a href="{% url 'ja_social:volunteer_record_log'%}">+</a></span></h1>
    <div id="hours-table-holder" class="col-sm-4 col-sm-offset-4">
      <table id="hours-table" class="display" cellspacing="0" width="100%">
        <thead>
          <tr>
            <th>Program</th>
            <th>Hours</th>
          </tr>
        </thead>
          {% for o in hours %}
            {% if o.user_profile == object %}
                {% if o.verified is True %}
                <tr>
                    <td>
                        {{ o.JA_program }}
                    </td>
                    <td>
                        {{ o.hours }}
                    </td>
                </tr>
          {% endif %}
            {% endif %}
          {% endfor %}
      </table>
    </div>
  </div>

<hr>


  <div id="photos-container" class="row">
    <h1>Photos<span class="edit_symbol"><a href="{% url 'ja_social:photo_upload'%}"> + </a></span></h1>
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
          <div class="row">
          {% for photo in photos %}
              <div class="col-xs-6 col-md-3">
                <a href="#" class="thumbnail">
                    <img class="photo_thumbnail" src="{{ photo.photo.url }}">
                </a>
                </div>
              {% endfor %}
        </div>

      </div>
    </div>
  </div>


{% endblock %}

ja_social/templates/user_register.html
{% extends 'base_html.html' %}
{% load static  %}
{% block title %}Register{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'ja_social/css/registration-style.css'%}">
{% endblock %}
{% block content %}
<div class="row">
   <div class="col-sm-8 col-sm-offset-2">
      <div class="jumbotron">
         <h1 id="featured-title">Registration</h1>
         <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
               <form action="" method="post">
                  {% csrf_token %}
                  <table>

                     {% for field in form %}
                     <tr>
                        <td>
                           {{ field.label_tag }}
                        </td>
                        <td>
                           {{ field }}
                        </td>
                         <td class="error_msg">
                             {{field.errors}}
                         </td>
                     </tr>
                     {% endfor %}
                  </table>
                  <input type="submit" value="Register">
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
{% endblock %}